Repository pedaling/class101-ui, pull requests merged in 2019-11, with the labels that each got.

#144 fix: react-router Link에 의해 스타일이 덮어쓰이는 것을 수정한다
  src/components/Button/ContainButton/index.tsx
  src/components/Button/TextButton/index.tsx
Labels: size/S

#143 feat: Section 컴포넌트의 linkText를 추가한다
  docs/components/Section.mdx
  src/layout/Section/Header.tsx
  src/layout/Section/index.tsx
Labels: size/L

#147 fix: Section컴포넌트의 linkText의 margin을 수정한다
  src/layout/Section/Header.tsx
Labels: size/XS

#148 fix: Section title의 typo props받던 것을 누락해서 다시 추가한다
  src/layout/Section/Header.tsx
  src/layout/Section/index.tsx
Labels: size/L

#149 fix: comment content justify 속성 삭제
  src/components/Comment/Content/index.tsx
Labels: size/XS

#150 fix: Section titlestyle의 props를 export하고 옵셔널로 수정한다
  src/layout/Section/Header.tsx
  src/layout/Section/index.tsx
Labels: size/XS

#152 feat: badge icon의 size를 number로 받았을 때는 icon이 60%을 차지하게 변경
  src/components/Badge/index.tsx
Labels: size/S

#156 chore: typescript와 prettier버전 올리고 lint
  .babelrc
  package.json
  src/components/Carousel/index.tsx
  src/components/Comment/Action/index.tsx
  src/components/Tabs/index.tsx
  src/formControls/RadioButtonGroup/index.tsx
  src/formInputs/Input/index.tsx
  src/formInputs/TagInput/InnerTags/index.tsx
  src/layout/Divider/index.tsx
  src/overlays/ModalBottomSheet/index.tsx
  yarn.lock
Labels: size/L

#157 feat: header를 class component로 변경
  package.json
  src/layout/Section/Header.tsx
Labels: size/M

#158 fix: build 오류를 수정한다
  package.json
  src/components/Comment/Content/index.tsx
  yarn.lock
Labels: size/S

#160 feat: carousel에 onInit 이벤트를 추가
  package.json
  src/components/Carousel/index.tsx
Labels: size/XS

#161 feat: comment click이벤트 추가 및 디자인 수정
  docs/components/Comment.mdx
  src/components/Avatar/index.tsx
  src/components/Badge/index.tsx
  src/components/Comment/Action/index.tsx
  src/components/Comment/Content/index.tsx
  src/components/Comment/index.tsx
Labels: size/M

#162 feat: Navigation에 external로 새 창 열기를 할 수 있다
  docs/components/Button.mdx
  docs/components/IconButton.mdx
  docs/components/Navigation.mdx
  docs/components/TextButton.mdx
  src/components/Button/ButtonBase/index.tsx
  src/components/Navigation/NavigationSection/index.tsx
  src/components/Navigation/index.tsx
  src/core/LinkBlock/index.tsx
  src/core/index.ts
Labels: size/L
