Repository pedaling/class101-ui, pull requests merged in 2019-08, with the labels that each got.

#81 feat: 버튼의 컬러를 추가한다
  docs/components/Button.mdx
  docs/components/TextButton.mdx
  src/components/Button/color.ts
  src/components/Button/interface.ts
Labels: size/M

#82 fix: control group의 fill이 먹히지 않는 버그를 수정한다
  docs/formControls/ControlGroup.mdx
  docs/formControls/ControlGroup.tsx
  src/components/ControlGroup/index.tsx
  src/components/index.ts
  src/index.ts
Labels: size/M

#83 fix: loading 상태도 className을 내려받아야한다
  src/components/Button/TextButton/index.tsx
  src/components/Button/index.tsx
Labels: size/XS

#84 fix: Button의 align을 수정한다
  docs/components/ButtonGroup.mdx
  src/components/Button/index.tsx
  src/components/ButtonGroup/index.tsx
Labels: size/S

#86 feat: IconButton을 추가한다
  docs/HelpComponents.tsx
  docs/components/Button.mdx
  docs/components/IconButton.mdx
  docs/components/TextButton.mdx
  src/components/Button/ButtonBase/index.tsx
  src/components/Button/ButtonIcon/index.tsx
  src/components/Button/ButtonSpinner/index.tsx
  src/components/Button/ContainButton/index.tsx
  src/components/Button/IconButton/index.tsx
  src/components/Button/TextButton/index.tsx
  src/components/Button/color.ts
  src/components/Button/index.tsx
  src/components/Button/interface.ts
  src/components/Button/utils.ts
  src/components/ButtonGroup/index.tsx
  src/components/Callout/index.tsx
  src/components/Callout/interface.ts
  src/components/Carousel/ViewAllButton/index.tsx
  src/components/index.ts
Labels: size/XXL

#88 feat: checkbox 에 disabled 요소를 추가한다
  src/Checkbox/index.tsx
Labels: size/S

#90 fix: 캐러셀 버튼이 disabled일 때 뒤의 요소가 클릭되지 않도록 한다
  docs/components/Carousel.mdx
  src/GlobalStyle/swiperDefaultStyle.ts
  src/components/Button/IconButton/index.tsx
  src/components/Carousel/Navigation/NavigationButton/index.tsx
  src/components/Carousel/Navigation/index.tsx
Labels: size/M

#96 fix: Chevron 삭제된 것 반영
  src/BottomSheet/index.tsx
  src/Section/Header.tsx
  src/components/Carousel/Navigation/NavigationButton/index.tsx
Labels: size/S

#93 Chore: now로 배포하도록 한다
  .gitignore
  .nowignore
  README.md
  doczrc.js
  now.json
  package.json
Labels: size/M

#98 feat: Add Modal BottomSheet
  docs/overlays/ModalBottomSheet.mdx
  docs/overlays/ModalBottomSheet.tsx
  src/overlays/ModalBottomSheet/index.tsx
  src/overlays/index.ts
  yarn.lock
Labels: size/L

#100 feat: 아이콘을 추가한다
  src/Icon/generated/Close.tsx
  src/Icon/generated/PaperOutline.tsx
  src/Icon/generated/Sorting.tsx
  src/Icon/generated/Square.tsx
  src/Icon/index.ts
  src/Icon/svgs/paper-outline.svg
  src/Icon/svgs/sorting.svg
  src/Icon/svgs/square.svg
Labels: size/M

#102 fix: ModalBottomSheet 모바일일때 padding bottom 24px로 수정
  src/overlays/ModalBottomSheet/index.tsx
Labels: size/XS
