Repository pedaling/class101-ui, pull requests merged in 2019-12, with the labels that each got.

#159 [BREAKING CHANGE] feat: GridListCompnent에 generic을 추가한다
  src/layout/GridList/index.tsx
  src/utils/index.ts
  src/utils/mapArray.ts
Labels: size/S

#166 fix: set nullable props in Skeleton
  src/components/Skeleton/Skeleton.tsx
Labels: size/XS

#167 Revert "[BREAKING CHANGE] feat: GridListCompnent에 generic을 추가한다"
  src/layout/GridList/index.tsx
  src/utils/index.ts
  src/utils/mapArray.ts
Labels: size/S

#169 feat: support darkTheme for skeleton component
  package.json
  src/components/Skeleton/Skeleton.tsx
Labels: size/S

#171 feat: comment 컴포넌트 readMoreText, hideText 추가 및 Action cursor 추가
  docs/components/Comment.mdx
  src/components/Comment/Action/index.tsx
  src/components/Comment/Content/index.tsx
  src/components/Comment/index.tsx
Labels: size/M
