Repository pedaling/class101-ui, pull requests merged in 2019-09, with the labels that each got.

#106 fix: switch 구조를 수정한다
  docs/docsComponents/HelpComponents/index.tsx
  docs/overlays/Modal.mdx
  src/components/Button/ButtonBase/index.tsx
  src/formInputs/Switch/index.tsx
Labels: size/L

#108 feat: Add NavigationContainerMaxWidth property
  docs/components/Carousel.mdx
  src/components/Carousel/Navigation/index.tsx
  src/components/Carousel/index.tsx
Labels: size/M

#107 feat: ModalBottomSheet 타이틀에 '\n'으로 줄바꿈 가능하게 한다
  src/overlays/ModalBottomSheet/index.tsx
Labels: size/S

#109 refactor: Modify style of the carousel navigation max-width attribute
  docs/components/Carousel.mdx
  src/components/Carousel/Navigation/index.tsx
Labels: size/S

#110 feat: modalBottomSheet에 success, cancel Attributes추가
  src/overlays/ModalBottomSheet/index.tsx
Labels: size/S

#111 fix: modalBottomSheet BottonProps를 Partial로 수정
  docs/overlays/ModalBottomSheet.mdx
  src/overlays/ModalBottomSheet/index.tsx
Labels: size/S

#112 feat: 포트를 3003으로고정
  doczrc.js
Labels: size/XS

#113 fix: modalBottomSheet 모바일에서 padding 15px되는 오류 수정
  src/overlays/ModalBottomSheet/index.tsx
Labels: size/M

#115 feat: 디펜덴시 정리
  package.json
Labels: size/S

#116 refacor: use class101 carousel
  docs/components/Carousel.mdx
  package.json
  src/components/Carousel/index.tsx
  yarn.lock
Labels: size/L

#118 feat: modalBottomSheet에 onOpen기능 추가
  docs/overlays/ModalBottomSheet.mdx
  src/overlays/ModalBottomSheet/index.tsx
Labels: size/S

#119 feat: added disabled buttons in numeric input
  docs/formInputs/NumericInput.mdx
  src/formInputs/NumericInput/index.tsx
Labels: size/S

#120 refactor: add minValue and maxValue in numericInput
  docs/formInputs/NumericInput.mdx
  src/formInputs/NumericInput/index.tsx
Labels: size/S

#117 feat: update rollup and analyze bundle
  .gitignore
  package.json
  rollup.config.js
  yarn.lock
Labels: size/XL

#121 feat: 태그인풋 사용성 개선
  docs/formInputs/TagInput.mdx
  src/components/Tag/index.tsx
  src/formInputs/InlineError/index.tsx
  src/formInputs/TagInput/InnerTags/index.tsx
  src/formInputs/TagInput/index.tsx
Labels: size/L

#122 fix: TextButton lineHeight 스타일을 수정한다
  src/components/Button/ButtonBase/index.tsx
  src/components/Button/TextButton/index.tsx
Labels: size/S

#123 feat: 태그인풋 개선
  src/formInputs/TagInput/index.tsx
Labels: size/S
