Repository pedaling/class101-ui, pull requests merged in 2019-06, with the labels that each got.

#61 feat: slidesBetween 설정을 추가한다
  docs/components/Carousel.mdx
  src/Button/index.tsx
  src/components/Carousel/Navigation/index.tsx
  src/components/Carousel/ViewAllButton/index.tsx
  src/components/Carousel/index.tsx
Labels: size/M

#62 refactor: 캐러셀 children 변경시 swiper가 update 되도록 한다
  src/components/Carousel/index.tsx
Labels: size/S

#63 feat: freeMode옵션을 추가한다
  src/components/Carousel/index.tsx
Labels: size/XS

#64 style: carousel ipad에서 아이콘 크기가 깨진다
  src/components/Carousel/Navigation/NavigationButton/index.tsx
Labels: size/XS

#66 feat: callout 컴포넌트를 추가한다
  docs/components/Callout.mdx
  src/components/Callout/index.tsx
  src/components/index.ts
Labels: size/L

#67 fix: Anchor button disabeld
  docs/components/Button.mdx
  src/Button/index.tsx
Labels: size/S
