Repository pedaling/class101-ui, pull requests merged in 2019-10, with the labels that each got.

#125 fix: modalBottomSheet ssr에서 나타나는 오류 수정
  src/overlays/ModalBottomSheet/index.tsx
  src/utils/ssr.ts
Labels: size/XS

#127 feat: ModalBottomSheet z-index 수정
  src/overlays/ModalBottomSheet/index.tsx
Labels: size/XS

#128 fix: iconPosition warning error 수정
  src/components/Button/ButtonBase/index.tsx
Labels: size/S

#130 fix: 린트 업뎃
  .eslintrc
  package.json
  tslint.json
  yarn.lock
Labels: size/XL

#135 feat: added eslint-plugin-prettier
  package.json
  yarn.lock
Labels: size/XS

#134 fix: modalBottomSheet max-height 를 100vh에서 window.innerHeight로 수정
  src/overlays/ModalBottomSheet/index.tsx
Labels: size/M

#137 feat: GridList items에 ReadonlyArray도 받도록 타이핑한다
  src/layout/GridList/index.tsx
Labels: size/XS

#139 fix: set id when SSR
  src/components/Carousel/index.tsx
  src/components/Swiper/index.tsx
Labels: size/M

#141 fix: utils import 방식을 상대경로로 변경해서 빌드에러 제거
  src/components/Swiper/index.tsx
Labels: size/XS
