Repository pedaling/class101-ui, pull requests merged in 2020-02, with the labels that each got.

#184 feat(ui): Avatar의 이미지를 좀 더 보기 좋게 변경
  src/components/Avatar/index.tsx
Labels: size/XS

#187 feat(ui): 그림자값 명세에 맞게 변경
  src/core/ElevationStyles/index.tsx
Labels: size/XS

#188 fix: elevation4, 5의 값을 수정한다
  src/core/ElevationStyles/index.tsx
Labels: size/XS

#190 docs(ui): 내용을 영문으로 바꾸고, 어색한 스타일을 정리한다
  docs/components/Avatar.mdx
  docs/components/Badge.mdx
  docs/components/Card.mdx
  docs/components/Divider.mdx
  docs/components/Icon.mdx
  docs/components/Pagination.mdx
  docs/components/Skeleton.mdx
  docs/core/Colors.mdx
  docs/core/ElevationStyles.mdx
  docs/index.mdx
  doczrc.js
Labels: size/L

#189 feat(ui, mdx): Pagination에 많은 데이터가 들어와도 적당히 대응 가능하게 수정
  docs/components/Pagination.mdx
  src/components/Pagination/index.tsx
Labels: size/M

#191 ModalBottomSheet 컴포넌트 제목 스타일 수정
  src/overlays/ModalBottomSheet/index.tsx
Labels: size/XS

#193 fix(ui): Swiper의 페이지네이션 영역이 클릭 이벤트를 차단하는 문제를 수정
  src/core/GlobalStyle/swiperDefaultStyle.ts
Labels: size/XS

#195 fix(ui): ModalBottomSheet의 subTitle, body가 길어질 때 줄바꿈한다
  src/overlays/ModalBottomSheet/index.tsx
Labels: size/XS

#196 feat(ui): Spinner의 컬러를 조정
  docs/components/Spinner.mdx
  src/components/Spinner/index.tsx
Labels: size/S

#197 feat(ui): Icon.category 컴포넌트의 아이콘을 변경한다
  src/Icon/generated/Category.tsx
  src/Icon/svgs/category.svg
Labels: size/S

#198 refactor: Spinner 메모이제이션 및 코드 개선
  docs/components/Spinner.mdx
  docs/components/Spinner.tsx
  src/components/Spinner/index.tsx
Labels: size/M

#200 fix: picker input 이슈들 수정
  src/formInputs/DatePicker/index.tsx
Labels: size/M

#206 chore: class101-ui 버전을 8.2.0으로 올린다
  package.json
Labels: size/XS

#209 feat: Badge의 디자인 변경
  docs/components/Badge.mdx
  src/components/Badge/index.tsx
Labels: size/S
