Repository pedaling/class101-ui, pull requests merged in 2020-07, with the labels that each got.

#281 feat: swiper에 fade effect를 적용할 수 있게 한다
  docs/components/Swiper.mdx
  src/components/Swiper/index.tsx
Labels: size/M

#282 feat: _blank target의 Link에 noopener을 제거한다
  src/core/Link/index.tsx
Labels: size/XS

#283 feat: swiper navigation 스타일 오버라이딩이 적용되지 않는 문제를 수정한다
  src/components/Swiper/ArrowNavigation/index.tsx
  src/components/Swiper/DefaultNavigation/index.tsx
Labels: size/L

#284 fix: swiper DefaultNavigation의 버튼이 disabled일 때 뒤의 영역이 클릭되지 않게 한다
  src/components/Swiper/DefaultNavigation/index.tsx
Labels: size/XS
