Repository pedaling/class101-ui, pull requests merged in 2020-11, with the labels that each got.

#299 fix: 네비게이션 메뉴 스타일을 수정한다
  src/components/Navigation/NavigationSection/index.tsx
Labels: size/M

#300 docs: 카피라이트 연도와 옛날 URL을 수정한다
  README.md
Labels: size/XS

#302 chore: eslint를 걷어내고 tslint를 적용한다.
  .lintstagedrc
  package.json
  tslint.json
  yarn.lock
Labels: size/XL

#303 feat: TagInput, Tag에서 disabled인 상태이면 CloseButton을 안 보이도록 한다.
  src/components/Tag/index.tsx
  src/formInputs/TagInput/index.tsx
Labels: size/S

#304 fix(ui): 영미권에서 break-all 속성으로 글자가 부자연스러운 현상을 해결한다
  src/overlays/ModalBottomSheet/ModalBottomSheet.tsx
Labels: size/XS
