Repository pedaling/class101-ui, pull requests merged in 2020-05, with the labels that each got.

#238 fix(ui): DatePicker에서 props가 바뀔 때 input 값이 안바뀌는 오류를 수정한다.
  src/formInputs/DatePicker/index.tsx
Labels: size/S

#239 feat(ui): ModalBottomSheet에 BottomButtonType prop을 추가한다.
  docs/overlays/ModalBottomSheet.mdx
  src/overlays/ModalBottomSheet/ModalBottomSheet.tsx
Labels: size/M

#243 style(ui): ModalBottomSheet의 Column타입 스타일을 수정한다.
  src/overlays/ModalBottomSheet/ModalBottomSheet.tsx
Labels: size/XS

#244 fix: 날짜 범위를 수정한다
  src/formInputs/DatePicker/MonthCalendar/index.tsx
  src/formInputs/DatePicker/index.tsx
Labels: size/S

#245 refactor(web): Pagination 컴포넌트에서 className을 받게한다
  src/components/Pagination/index.tsx
Labels: size/XS

#247 class ui 버전을 v9.0.0-rc13 으로 올린다
  package.json
Labels: size/XS

#249 chore(docs): gatsby-plugin-styled-components를 적용한다
  gatsby-config.js
  package.json
  yarn.lock
Labels: size/S

#252 fix: carousel 컴포넌트에 padding이 적용안되는 이슈 수정
  src/components/Carousel/index.tsx
Labels: size/M

#253 feat: Badge icon을 추가한다
  src/Icon/generated/Badge.tsx
  src/Icon/index.ts
  src/Icon/svgs/Badge.svg
Labels: size/M

#254 Revert "feat: Badge icon을 추가한다"
  src/Icon/generated/Badge.tsx
  src/Icon/index.ts
  src/Icon/svgs/Badge.svg
Labels: size/M

#257 fix: NumericInput 컴포넌트의 증가/감소 버튼 스타일이 깨지는 문제 수정
  src/formInputs/NumericInput/index.tsx
Labels: size/XS

#258 feat(ui): modal bottom sheet에 min height를 제거한다
  src/overlays/ModalBottomSheet/ModalBottomSheet.tsx
Labels: size/XS

#262 chore: size-limit 적용할 파일을 glob 패턴을 사용해 찾지 않고 직접 지정한다
  .size-limit.json
Labels: size/XS

#263 feat(web): clap, clapOutilne, fullScreenExit, fullScreen 아이콘을 변경한다
  src/Icon/generated/Clap.tsx
  src/Icon/generated/ClapOutline.tsx
  src/Icon/generated/FullScreen.tsx
  src/Icon/generated/FullScreenExit.tsx
  src/Icon/svgs/Clap.svg
  src/Icon/svgs/ClapOutline.svg
  src/Icon/svgs/FullScreen.svg
  src/Icon/svgs/FullScreenExit.svg
Labels: size/M

#259 feat(ui): DatePicker에 time을 추가한다.
  docs/formInputs/DatePicker.mdx
  src/formInputs/DatePicker/MonthCalendar/Day/index.tsx
  src/formInputs/DatePicker/MonthSelector/Month/index.tsx
  src/formInputs/DatePicker/MonthSelector/index.tsx
  src/formInputs/DatePicker/TimeSelector/Input/index.tsx
  src/formInputs/DatePicker/TimeSelector/index.tsx
  src/formInputs/DatePicker/index.tsx
  src/formInputs/DatePicker/interface.ts
  src/formInputs/DatePicker/locales/en_US.ts
  src/formInputs/DatePicker/locales/ko_KR.ts
  src/utils/padNumber.ts
Labels: size/L

#264 fix(ui): DatePicker time이 잘못 표시되는 오류를 수정한다
  src/formInputs/DatePicker/index.tsx
Labels: size/XS
