Repository pedaling/class101-ui, pull requests merged in 2020-06, with the labels that each got.

#265 fix: 캐러셀 smSlidesSideOffset이 제대로 적용되지 않는 걸 수정한다
  src/components/Carousel/index.tsx
Labels: size/M

#266 fix(ui): DatePicker time에 form을 삭제한다
  src/formInputs/DatePicker/TimeSelector/Input/index.tsx
Labels: size/S

#267 fix(ui): DatePicker의 Range 버그를 수정한다.
  src/formInputs/DatePicker/MonthCalendar/Day/index.tsx
  src/formInputs/DatePicker/MonthCalendar/index.tsx
Labels: size/M

#269 feat: Reply 컴포넌트 추가
  docs/components/Comment.mdx
  docs/components/Reply.mdx
  src/components/Badge/index.tsx
  src/components/Reply/Action/index.tsx
  src/components/Reply/Content/index.tsx
  src/components/Reply/index.tsx
  src/components/index.ts
Labels: size/XL

#270 fix(ui): Input의 Warning들을 제거한다.
  src/formInputs/Input/index.tsx
Labels: size/XS

#271 fix: rangeValue props가 변경되었을때 달력이 변경되지 않는 버그를 수정한다
  docs/formInputs/DatePicker.mdx
  src/formInputs/DatePicker/index.tsx
Labels: size/M

#272 docs: DatePicker 외부 state로 관리하기 부분을 수정한다
  docs/formInputs/DatePicker.mdx
Labels: size/S

#273 feat(web): 댓글 컴포넌트에서 "전체보기" 버튼을 숨길 수 있는 hideReadMore값을 추가한다.
  src/components/Comment/Content/index.tsx
  src/components/Comment/index.tsx
  src/components/Reply/Content/index.tsx
  src/components/Reply/index.tsx
Labels: size/S

#274 feat(ui): Toast 메세지에 줄바꿈이 가능하도록 수정한다.
  src/overlays/Toast/index.tsx
  src/utils/index.ts
Labels: size/XS

#275 fix: removeContentPadding의 모바일 스타일 버그를 수정한다
  src/overlays/ModalBottomSheet/ModalBottomSheet.tsx
Labels: size/S

#277 chore(ui): swiper의 모듈을 추가한다
  src/components/Swiper/index.tsx
Labels: size/S

#279 fix(web): input에 ref가 동작하도록 수정한다.
  src/formInputs/Input/index.tsx
Labels: size/XS

#280 fix(ui): Tag 컴포넌트의 x 표시 위치를 수정한다
  src/components/Tag/index.tsx
Labels: size/XS

#278 fix: Comment, Reply 컴포넌트에 이벤트 전파를 막는다
  src/components/Comment/index.tsx
  src/components/Reply/index.tsx
Labels: size/XS
