Repository pedaling/class101-ui, pull requests merged in 2020-04, with the labels that each got.

#223 chore(docs): docs width 오타 수정
  docs/components/Skeleton.mdx
Labels: size/XS

#220 feat(ui): Overlay 컴포넌트를 추가한다.
  docs/overlays/OverlaidPortal.mdx
  src/overlays/ModalBottomSheet/index.tsx
  src/overlays/OverlaidPortal/index.tsx
  src/overlays/index.ts
Labels: size/L

#224 fix: tooltip이 prop에 따라 열고닫도록 수정
  src/overlays/Tooltip/index.tsx
Labels: size/XS

#229 feat(ui) elevation 변경 사항을 적용한다.
  src/core/ElevationStyles/index.tsx
Labels: size/S

#230 Refactor/carousel docs
  docs/components/Carousel.mdx
Labels: size/L

#231 fix: LinkComponentProps의 optional여부를 수정한다
  src/contexts/LinkContext/index.tsx
  src/core/Link/index.tsx
Labels: size/XS

#233 fix(ui): docz PropsTable이 정상적으로 표시되도록 수정한다.
  doczrc.js
Labels: size/XS

#234 fix(ui): searchPatterns 우선순위를 수정한다.
  doczrc.js
Labels: size/XS

#232 fix: 모달 오픈시 화면이 떨리는 현상을 해결한다
  src/overlays/Modal/Modal.tsx
  src/overlays/ModalBottomSheet/ModalBottomSheet.tsx
  src/utils/fixScrollbar.ts
  src/utils/index.ts
Labels: size/M
