Repository pedaling/class101-ui, pull requests merged in 2020-01, with the labels that each got.

#172 fix: Comment컴포넌트 더보기 버튼 preventDefault 적용
  src/components/Comment/Content/index.tsx
Labels: size/XS

#174 fix: tagInput에서 첫번째 태그 삭제할 때 전체가 날라가는 버그를 수정한다
  docs/formInputs/TagInput.mdx
  src/formInputs/TagInput/index.tsx
Labels: size/M

#175 fix: tagInput 5000개 이상일 경우 모두 삭제되게 한다
  docs/formInputs/TagInput.mdx
  src/formInputs/TagInput/index.tsx
Labels: size/M

#176 feat: TextButton에 XSMALL을 추가한다
  docs/components/TextButton.mdx
  src/components/Button/ButtonIcon/index.tsx
  src/components/Button/TextButton/index.tsx
  src/components/Button/interface.ts
Labels: size/S

#178 fix: modalBottomSheet에 className 받게 하고 title ReactNode로 변경한다
  src/overlays/ModalBottomSheet/index.tsx
Labels: size/M

#177 feat: AnchorButton 추가
  docs/components/Button.mdx
  src/components/Button/AnchorButton/index.tsx
  src/components/Button/AnchorButtonBase/index.tsx
  src/components/Button/ButtonBase/index.tsx
  src/components/Button/index.tsx
Labels: size/L

#179 feat: comment action에 hidden 속성 추가
  docs/components/Comment.mdx
  src/components/Comment/Action/index.tsx
Labels: size/S

#180 feat(ui): 툴팁 컴포넌트를 추가한다
  docs/overlays/Tooltip.mdx
  docs/overlays/Tooltip.tsx
  package.json
  src/core/Position/index.ts
  src/overlays/Tooltip/colors.ts
  src/overlays/Tooltip/index.tsx
  src/overlays/Tooltip/utils.ts
  src/overlays/index.ts
  yarn.lock
Labels: size/L

#181 fix(ui): tooltip에 styled가 적용되지 않는 문제를 수정한다
  docs/overlays/Tooltip.mdx
  docs/overlays/Tooltip.tsx
  src/overlays/Tooltip/index.tsx
Labels: size/S

#182 fix: light 버튼의 disabled text color를 조정한다
  src/components/Button/color.ts
Labels: size/XS
