Repository pedaling/class101-ui, pull requests merged in 2020-03, with the labels that each got.

#210 fix: Badge의 아이콘 얼라인을 수정한다
  src/components/Badge/index.tsx
Labels: size/XS

#211 feat(ui): RadioIcon의 border-width를 늘린다
  src/formControls/RadioButtonGroup/RadioButton/RadioIcon.tsx
Labels: size/XS

#214 feat(ui): TextStyles letter-spacing, line-height 수정 (feat. 쿤)
  src/core/TextStyles/index.tsx
Labels: size/S

#217 refactor: ModalBottomSheet의 dialog max-height을 % 기준으로 계산한다
  src/overlays/ModalBottomSheet/index.tsx
Labels: size/M

#218 refactor: skeleton의 layout관련 props들은 inlineStyle로 적용한다
  src/components/Skeleton/Skeleton.tsx
Labels: size/M

#219 chore: v9.0.0-rc1
  package.json
Labels: size/XS
