Repository pedaling/class101-ui, pull requests merged in 2020-12, with the labels that each got.

#305 fix: TagInput에서 disabled일때 CloseButton이 뜨던 버그를 수정한다.
  src/components/Tag/index.tsx
  src/formInputs/TagInput/index.tsx
Labels: size/S

#306 fix: ModalBottomSheet에서 영어가 단어 단위로 줄바꿈 되도록 수정한다.
  src/overlays/ModalBottomSheet/ModalBottomSheet.tsx
Labels: size/M

#308 fix: ModalBottomSheet의 title과 subTitle간의 간격을 줄인다
  src/overlays/ModalBottomSheet/ModalBottomSheet.tsx
Labels: size/XS
