Repository pedaling/class101-ui, pull requests merged in 2021-05, with the labels that each got.

#334 fix: Reply Action에 Icon Prop을 Optional 값으로 수정한다
  src/components/Reply/Action/index.tsx
Labels: size/S

#341 style: 기존 아이콘 사용 방식에 `@deprecated` 처리를 한다
  src/Icon/index.ts
Labels: size/S

#342 refactor: Swiper, Carousel 컴포넌트를 함수형으로 리팩토링한다
  docs/components/Carousel.mdx
  src/components/Carousel/index.tsx
  src/components/Swiper/ArrowNavigation/index.tsx
  src/components/Swiper/DefaultNavigation/index.tsx
  src/components/Swiper/Slide/index.tsx
  src/components/Swiper/index.tsx
  src/components/index.ts
Labels: size/L

#343 fix: `Carousel` 컴포넌트에 `children` 타입을 추가한다
  src/components/Carousel/index.tsx
Labels: size/XS

#344 fix: `Carousel` 컴포넌트 프롭을 Optional 하게 설정한다
  src/components/Carousel/index.tsx
Labels: size/XS

#347 Button to functional new
  src/components/Button/ButtonBase/index.tsx
  src/components/Button/ContainButton/index.tsx
  src/components/Button/IconButton/index.tsx
  src/components/Button/TextButton/index.tsx
  src/components/Button/utils.ts
Labels: size/L

#348 refac(web): NumericInput to functional component
  src/formInputs/DatePicker/index.tsx
  src/formInputs/Input/index.tsx
  src/formInputs/NumericInput/index.tsx
Labels: size/L

#349 fix: RadioButtonGroup 의 자식들을 배열로 매핑해두면 경고가 나오는것을 고친다
  src/formControls/RadioButtonGroup/index.tsx
Labels: size/XS

#350 fix(web): set DefaultValue of Input component
  src/formInputs/Input/index.tsx
Labels: size/M

#351 refac: NumbericInput to functional component
  src/formInputs/NumericInput/index.tsx
Labels: size/L

#352 change InputType to type
  src/formInputs/DatePicker/index.tsx
  src/formInputs/Input/index.tsx
  src/formInputs/Select/index.tsx
  src/formInputs/common.ts
Labels: size/S
