Repository pedaling/class101-ui, pull requests merged in 2021-06, with the labels that each got.

#353 fix: button style fix
  src/components/Button/ButtonBase/index.tsx
Labels: size/XS

#354 feat: `swiper` 패키지 버전을 `6.7.0`으로 올린다
  docs/components/Carousel.mdx
  package.json
  src/components/Carousel/index.tsx
  src/components/Swiper/Slide/index.tsx
  src/components/Swiper/index.tsx
  src/core/GlobalStyle/swiperDefaultStyle.ts
  yarn.lock
Labels: size/XXL

#356 chore: 배포를 쉽게 할 수 있는 `yarn npm-publish` 명령어를 추가한다
  package.json
Labels: size/XS

#355 refac: Tag to functional
  src/components/Tag/index.tsx
  src/formInputs/TagInput/InnerTags/index.tsx
  src/formInputs/TagInput/index.tsx
Labels: size/L

#358 fix: 롤업 빌드가 이상하게 되던 문제를 해결한다
  package.json
  rollup.config.js
  yarn.lock
Labels: size/S

#360 fix swiper slide
  src/components/Swiper/index.tsx
Labels: size/S
